name: Deploy portal-b to Pages

on:
  push:
    branches: ["main"] # main 브랜치에 코드가 올라오면 실행

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'portal-b/pnpm-lock.yaml'

      - name: Install dependencies and Build
        run: |
          cd portal-b
          pnpm install
          pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'portal-b/dist' # 빌드 완료된 결과물 폴더 위치

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
